### ISSUE TITLE
Missing "./src/Portal.svelte" specifier in "svelte-portal" package

### ISSUE THREAD

**Issue by TheOnlyTails** [ryu-man/svelte-fui#32]
Hello, I'm attempting to migrate the [Files](https://files.community/) website to use this package, but I'm running into an issue where attempting to use it gives this error for the Dropdown, Combobox, and Dialog components:
```
 node_modules/.pnpm/@svelte-fui+core@0.2.0_@floating-ui+dom@1.6.5_@svelte-fui+theme@0.1.3_lodash-es@4.17.21__@sve_gehesxgxlhubml4etwrcre56qy/node_modules/@svelte-fui/core/dist/dialog/Dialog.svelte:38:19:
      38 │ import Portal from "svelte-portal/src/Portal.svelte";
         ╵                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I believe converting the imports to `import Portal from "svelte-portal"` will fix this issue.
Looking forward to use this package!

**Comment by ryu-man** [comment]
I will work on a fix

**Comment by ryu-man** [comment]
`svelte-portal` package will be emoved, and  an internal implementation will be used instead

**Comment by ryu-man** [comment]
@TheOnlyTails there is a new release with a fix for this issue, check `@svelte-fui/core@1.0.0-alpha.1`
