### ISSUE TITLE
Using the library with instructions in README gives a css error

### ISSUE THREAD

**Issue by Futuremappermydud** [ryu-man/svelte-fui#40]
I followed the directions in the README and got this error
![image](https://github.com/user-attachments/assets/a6abfe36-9670-49b0-aebf-42fb125b7868)
I tried adding the PostCSS lang to the file in the error but had no luck.

**Comment by ryu-man** [comment]
@Futuremappermydud try this POSTCSS configuration

```
export default {
	plugins: {
		'tailwindcss/nesting': {},
		tailwindcss: {},
		'postcss-preset-env': {
			features: { 'nesting-rules': false }
		},
		autoprefixer: {}
	}
};
```

If you are using tailwindcss then you might adjust your configuration to fit the following:

```
export default {
	content: [
		'./src/**/*.{html,js,svelte,ts}',
		'./node_modules/@svelte-fui/core/dist/**/*.{html,js,ts,svelte}'
	],
	presets: [fuiPreset],	
}
```

**Comment by ryu-man** [comment]
Or if you install the version `1.0.0-alpha.14` , if you nneed to use tailwindcss you still have to integrate the following configs in `tailwind.config.ts`:
```
import type { Config } from 'tailwindcss';
import { fuiPreset } from '@svelte-fui/tailwindcss';

export default {
	content: ['./src/**/*.{html,js,svelte,ts}', './node_modules/@svelte-fui/core/**/*.{html,js,svelte,ts}'],
	presets: [fuiPreset],
	theme: {
		extend: {}
	},

	plugins: []
} satisfies Config;
```

**Comment by ryu-man** [comment]
Going to close this issue as it should be solved

**Comment by Futuremappermydud** [comment]
> @Futuremappermydud try this `postcss` configuration
> 
> ```
> export default {
> 	plugins: {
> 		'tailwindcss/nesting': {},
> 		tailwindcss: {},
> 		'postcss-preset-env': {
> 			features: { 'nesting-rules': false }
> 		},
> 		autoprefixer: {}
> 	}
> };
> ```
> 
> If you are using tailwindcss then you might adjust your configuration to fit the following:
> 
> ```
> import type { Config } from 'tailwindcss';
> import { fuiPreset } from '@svelte-fui/tailwindcss';
> 
> export default {
> 	content: ['./src/**/*.{html,js,svelte,ts}', './node_modules/@svelte-fui/core/**/*.{html,js,svelte,ts}'],
> 	presets: [fuiPreset],
> 	theme: {
> 		extend: {}
> 	},
> 
> 	plugins: []
> } satisfies Config;
> ```

Worked, Thank you!
