### ISSUE TITLE
Using a dropdown and clicking anywhere outside of the dropdown causes the entire tab to close.

### ISSUE THREAD

**Issue by Futuremappermydud** [ryu-man/svelte-fui#44]
https://github.com/user-attachments/assets/affb4b79-1dc8-4a38-8334-ee719c65701b

[FilterView.svelte.txt](https://github.com/user-attachments/files/18174561/FilterView.svelte.txt)

Removing the Trigger part of the drop down specifically causes the issue to go away.

**Comment by ryu-man** [comment]
is that a browser tab? which browser is that?

**Comment by Futuremappermydud** [comment]
> is that a browser tab? which browser is that?

This is Zen Browser, based on Firefox.

**Comment by Futuremappermydud** [comment]
> is that a browser tab? which browser is that?

Just confirmed it works on chrome. Might be due to the popover element actually using different windows on firefox(iirc?)

**Comment by Futuremappermydud** [comment]
Found it! Regularly opened tabs will give an error of `Scripts may only close windows that were opened by a script.` from dropdown-menu.svelte:62 which is just a close() function. But if you drag a link to that page then it will close the tab(somehow opened by script i guess)

**Comment by Futuremappermydud** [comment]
This actually affects chrome too.

**Comment by ryu-man** [comment]
@Futuremappermydud Well done, I am going to push a fix right away

**Comment by ryu-man** [comment]
Fixed in `@svelte-fui/core@1.0.0-alpha.15`
