### ISSUE TITLE
Unexpected Token Error with alpha 15

### ISSUE THREAD

**Issue by Futuremappermydud** [ryu-man/svelte-fui#46]
![image](https://github.com/user-attachments/assets/c2cd71fc-1f44-4ecb-9a79-974cce582569)

Only updated from alpha 14->15 and got this error (sorry).

**Comment by ryu-man** [comment]
There is a problem with svelte package; it did not strip out typescript syntax.

**Comment by ryu-man** [comment]
fixed in `1.0.0-alpha.16`
